### ISSUE TITLE
"[...] is not a gzip file"  

### ISSUE THREAD

**Issue by arokem** [templateflow/python-client#108] opened 2023-10-09 19:42 UTC
A pyAFQ user [reported](https://github.com/yeatmanlab/pyAFQ/issues/924) that they are seeing the following error: 

"nibabel.filebasedimages.ImageFileError: File C:\Users\Leqing Zhou\.cache\templateflow\tpl-MNI152NLin2009cAsym\tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz is not a gzip file" 

What should they do to recover from this state of affairs?

**Comment by arokem** [comment] 2023-10-09 19:44
cc @RosieZho, @ 66RuixiZheng

**Comment by mgxd** [comment] 2023-10-09 20:14
Seems like the file is corrupt - I'd try clearing the local templateflow directory (`$HOME/.cache/templateflow`) and redownload the data. You can use the following command, assuming you have templateflow installed in your current python environment.

```
python -c "import templateflow.api as tf; tf.get('MNI152NLin2009cAsym', resolution=1, desc=None, suffix='T1w')"
```

**Comment by 66RuixiZheng** [comment] 2023-10-10 02:07
I tried invoking the command and it still doesn't work, but the following warning appears, ‘repository not found at <C:\Users\Administrator\.cache\templateflow>. Populating a new TemplateFlow stub. If the path reported above is not the desired location for TemplateFlow, please set the TEMPLATEFLOW_HOME environment variable.’

**Comment by mgxd** [comment] 2023-10-10 14:01
Ah, I see you're on windows - you might want to check:
```
%userprofile%\.cache\templateflow
```

This should be the default location, but you can alter this by setting the `TEMPLATEFLOW_HOME` environment variable to a custom path.

**Comment by effigies** [comment] 2023-11-03 19:24
Is this still open? @rosiezho @66RuixiZheng @arokem

**Comment by oesteban** [comment] 2024-03-15 17:17
@RosieZho switched to a matlab version of AFQ so I assume templateflow is not used there.

@ZhengRuixi, did you resolve the issue?

Deleting the templateflow cache would be a first step to solve this.

**Comment by oesteban** [comment] 2024-03-15 17:20
@mgxd given the prevalence of this kind of issues when pulling from S3, we should probably check MD5 sums or try to open the file with nibabel after a download, don't you think?

**Comment by oesteban** [comment] 2024-03-15 17:23
I believe this is a duplicate of #53. Since my comment is sort of suggested there, let's move the conversation.

**Closed by oesteban** 2024-03-15 17:23 UTC
Labels: bug
